# Generated by Django 3.0.4 on 2020-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchForm_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=120)),
                ('searchterm', models.CharField(max_length=120)),
            ],
        ),
    ]
